author: Julian Castillo y Juan Pablo Fonseca
description: Escuela Colombiana de Ingenieria Julio Garavito

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
